export const fullYearDates = [
  // January 2025 (Starts on Wednesday)
  {
    month: "January",
    dates: [
      { num: 29, place: false },
      { num: 30, place: false },
      { num: 31, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 31, place: true },
      { num: 1, place: false },
    ],
  },
  // February 2025 (Starts on Saturday)
  {
    month: "February",
    dates: [
      { num: 26, place: false },
      { num: 27, place: false },
      { num: 28, place: false },
      { num: 29, place: false },
      { num: 30, place: false },
      { num: 31, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 1, place: false },
    ],
  },
  // March 2025 (Starts on Saturday)
  {
    month: "March",
    dates: [
      { num: 23, place: false },
      { num: 24, place: false },
      { num: 25, place: false },
      { num: 26, place: false },
      { num: 27, place: false },
      { num: 28, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 31, place: true },
      { num: 1, place: false },
      { num: 2, place: false },
      { num: 3, place: false },
      { num: 4, place: false },
      { num: 5, place: false },
    ],
  },
  // April 2025 (Starts on Tuesday)
  {
    month: "April",
    dates: [
      { num: 30, place: false },
      { num: 31, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 1, place: false },
      { num: 2, place: false },
      { num: 3, place: false },
    ],
  },
  // May 2025 (Starts on Thursday)
  {
    month: "May",
    dates: [
      { num: 27, place: false },
      { num: 28, place: false },
      { num: 29, place: false },
      { num: 30, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 31, place: true },
    ],
  },
  // June 2025 (Starts on Sunday)
  {
    month: "June",
    dates: [
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 1, place: false },
      { num: 2, place: false },
      { num: 3, place: false },
      { num: 4, place: false },
      { num: 5, place: false },
    ],
  },
  // July 2025 (Starts on Tuesday)
  {
    month: "July",
    dates: [
      { num: 29, place: false },
      { num: 30, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 31, place: true },
      { num: 1, place: false },
      { num: 2, place: false },
    ],
  },
  // August 2025 (Starts on Friday)
  {
    month: "August",
    dates: [
      { num: 27, place: false },
      { num: 28, place: false },
      { num: 29, place: false },
      { num: 30, place: false },
      { num: 31, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 31, place: true },
      { num: 1, place: false },
      { num: 2, place: false },
      { num: 3, place: false },
      { num: 4, place: false },
      { num: 5, place: false },
      { num: 6, place: false },
    ],
  },
  // September 2025 (Starts on Monday)
  {
    month: "September",
    dates: [
      { num: 31, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 1, place: false },
      { num: 2, place: false },
      { num: 3, place: false },
      { num: 4, place: false },
    ],
  },
  // October 2025 (Starts on Wednesday)
  {
    month: "October",
    dates: [
      { num: 28, place: false },
      { num: 29, place: false },
      { num: 30, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 31, place: true },
      { num: 1, place: false },
    ],
  },
  // November 2025 (Starts on Saturday)
  {
    month: "November",
    dates: [
      { num: 26, place: false },
      { num: 27, place: false },
      { num: 28, place: false },
      { num: 29, place: false },
      { num: 30, place: false },
      { num: 31, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 1, place: false },
      { num: 2, place: false },
      { num: 3, place: false },
      { num: 4, place: false },
      { num: 5, place: false },
      { num: 6, place: false },
    ],
  },
  // December 2025 (Starts on Monday)
  {
    month: "December",
    dates: [
      { num: 30, place: false },
      { num: 1, place: true },
      { num: 2, place: true },
      { num: 3, place: true },
      { num: 4, place: true },
      { num: 5, place: true },
      { num: 6, place: true },
      { num: 7, place: true },
      { num: 8, place: true },
      { num: 9, place: true },
      { num: 10, place: true },
      { num: 11, place: true },
      { num: 12, place: true },
      { num: 13, place: true },
      { num: 14, place: true },
      { num: 15, place: true },
      { num: 16, place: true },
      { num: 17, place: true },
      { num: 18, place: true },
      { num: 19, place: true },
      { num: 20, place: true },
      { num: 21, place: true },
      { num: 22, place: true },
      { num: 23, place: true },
      { num: 24, place: true },
      { num: 25, place: true },
      { num: 26, place: true },
      { num: 27, place: true },
      { num: 28, place: true },
      { num: 29, place: true },
      { num: 30, place: true },
      { num: 31, place: true },
      { num: 1, place: false },
      { num: 2, place: false },
      { num: 3, place: false },
    ],
  },
];

const fullYearMonths = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
